### ISSUE TITLE
selectdb/doris.broker-ubuntu does not have a 2.0.3 version image on dockerhub

### ISSUE THREAD

**Issue by shookM** [apache/doris-operator#112]
selectdb/doris.broker-ubuntu does not have a 2.0.3 version image on dockerhub .Unable to pull

**Comment by catpineapple** [comment]
done 
https://hub.docker.com/layers/selectdb/doris.broker-ubuntu/2.0.3/images/sha256-6dfbfb3907a0fb9ed62264c8a189b7f5a7c0f7a4bf58a407331507ee58672c9e?context=repo
