### ISSUE TITLE
请问下doc目录中的readme文档是使用什么框架构建的

### ISSUE THREAD

**Issue by H-TWINKLE** [apache/doris-operator#120]
请问下doc目录中的readme文档是使用什么框架构建的，想离线环境部署使用。

**Comment by intelligentfu** [comment]
你是说doc的那些md文档吗

**Comment by intelligentfu** [comment]
@H-TWINKLE 离线部署使用，把readme中的yaml下载下来。镜像准备好，另外注意一个点，就是doris有一个初始化image，https://hub.docker.com/repository/docker/selectdb/alpine/general 如果是私网环境，需要把这个初始化image推到私有仓库，部署的时候在be的spec里配置一下initImage
![image](https://github.com/selectdb/doris-operator/assets/130764377/5205982a-f9c7-45eb-a806-c3d1635049b9)
