### ISSUE TITLE
helm 安装通过命令行指定集群名和命令空间不生效

### ISSUE THREAD

**Issue by anthony-yau** [apache/doris-operator#126]
helm版本：v3.7.1

通过以下命令安装，指定集群名称和命名空间不生效：

helm install -n default doris-test ./ -f values.yaml 

输出提示：看上去是对的
NAME: doris-test
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing doris-1.4.1

但是还是部署到了doris的命名空间下，集群名称为：doriscluster-helm

看着是_helpers.tpl 里面设置的模板有些问题。

**Comment by intelligentfu** [comment]
helm 的 namespace 在使用的时候会有诸多限制，如果 namespace 不存在会直接报错，Doris helm 将 namespace 内置化到 values 里可以兜掉很多不必要的失败，暂时不考虑更改模板把 namespace 放出来，后期会看看如何兼容 helm 的namespace 的使用。

**Comment by catpineapple** [comment]
motify policy at #147
