### ISSUE TITLE
service can't be updated in k8s 1.19 version

### ISSUE THREAD

**Issue by intelligentfu** [apache/doris-operator#143]
![wecom-temp-243873-1f2d0af4ecd13ab5e96ce2dd26fd387e](https://github.com/selectdb/doris-operator/assets/130764377/e3059131-0f70-421d-910c-af020f410def)
when updating service for doris components.  operator crashed for clusterIP not set "".  Doris operator uses update mode to effect.

**Comment by intelligentfu** [comment]
similar to  #119 ， but #121 not finished this issue.

**Comment by catpineapple** [comment]
fixed #160
