### ISSUE TITLE
doris 能够部署成功，但更新yaml后重新部署，不自动重启be,fe等pod

### ISSUE THREAD

**Issue by ChangjunZhang** [apache/doris-operator#149]
operator报错2024-04-10T12:04:12Z    ERROR   Reconciler error        {"controller": "doriscluster", "controllerGroup": "doris.selectdb.com", "controllerKind": "DorisCluster", "DorisCluster": {"name":"doriscluster-zelos","namespace":"doris"}, "namespace": "doris", "name": "doriscluster-zelos", "reconcileID": "cb2fa73c-c75e-4f07-9807-388357fb09fb", "error": "Service \"doriscluster-zelos-fe-service\" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset"}

**Comment by intelligentfu** [comment]
@ChangjunZhang  what's the k8s version?

**Comment by ChangjunZhang** [comment]
> @ChangjunZhang what's the k8s version?

The version of Kubernetes I am using is v1.20.10. Is there a way to solve this problem?

**Comment by intelligentfu** [comment]
same with https://github.com/selectdb/doris-operator/issues/143

**Comment by catpineapple** [comment]
fixed #160
