### ISSUE TITLE
[BUG] 存算分离集群部署例子资源疑似有误

### ISSUE THREAD

**Issue by zhangbc97** [apache/doris-operator#222]
下列文件中的requests和limits疑似写反

https://github.com/selectdb/doris-operator/blob/adbf99c1b875daa1e46d0ee06dacf50f3320d144/doc/examples/disaggregated/metaservice/ddm-sample.yaml#L8

https://github.com/selectdb/doris-operator/blob/adbf99c1b875daa1e46d0ee06dacf50f3320d144/doc/examples/disaggregated/metaservice/ddm-ms-log-pv-sample.yaml#L8

**Comment by catpineapple** [comment]
hi，这个在当时的版本确实是提供了错误示例，在新的正式版中，我们调整了 DCR定义，这个配置已经不再使用，正式版请参考文档：https://doris.apache.org/docs/3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart
