### ISSUE TITLE
fe service支持下annotations的定义吗？

### ISSUE THREAD

**Issue by anthony-yau** [apache/doris-operator#65]
fe service可以支持下annotations的定义吗？

如阿里云服务使用负载均衡NLB：https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/configure-nlb-instances-by-using-annotations?spm=a2c4g.11186623.0.0.66822c7dq6iDV5
腾讯云使用负载均衡CLB：https://cloud.tencent.com/document/product/457/45491

**Comment by intelligentfu** [comment]
这个目前不支持，这个需求是合理的我们排期下一个小版本支持。

**Comment by intelligentfu** [comment]
fixed https://github.com/selectdb/doris-operator/pull/75
