### ISSUE TITLE
[bug]-按文档跑示例fe只能成功启动一个

### ISSUE THREAD

**Issue by seawenc** [apache/doris-operator#71]
参考文档： https://doris.apache.org/zh-CN/docs/install/k8s-deploy
``` bash
kubectl apply -f https://raw.githubusercontent.com/selectdb/doris-operator/master/config/crd/bases/doris.selectdb.com_dorisclusters.yaml    
kubectl apply -f https://raw.githubusercontent.com/selectdb/doris-operator/master/config/operator/operator.yaml
kubectl apply -f https://raw.githubusercontent.com/selectdb/doris-operator/master/doc/examples/doriscluster-sample.yaml
```
> 只是将名称`doriscluster-sample`修改了一下名称为了：`doriscluster`

![image](https://github.com/selectdb/doris-operator/assets/40030020/56b55493-ee16-48f6-ad55-93ed75bf3ce4)

错误信息：
```
ERROR (stateListener|97) [Env.checkCurrentNodeExist():1601] current node doriscluster-fe-1.doriscluster-fe-internal.doris.svc.cluster.local:9010 is not added to the cluster, will exit. Your FE IP maybe changed, please set 'priority_networks' config in fe.conf properly.
```

看提示是说需要设置priority_networks，我把，`fe.conf`加上以下参数,挂载到pod也没有任何效果:
```
priority_networks = 10.42.0.0/16
enable_fqdn_mode = true
```

![image](https://github.com/selectdb/doris-operator/assets/40030020/0a2a6aa7-fc65-40c1-895e-ae0be3447dd1)

请帮忙看看哪里有问题呢？

**Comment by intelligentfu** [comment]
贴一下环境信息：
什么机器类型，几台机器(目前mac不行)
系统资源是多少，
从报错看是脑裂，大概率是资源不足导致的通信资源被抢占导致服务通信异常，或者是服务之间网络有问题这些。
