### ISSUE TITLE
Unable to resolve 'be domain name' for accessing the k8s cluster from outside.

### ISSUE THREAD

**Issue by ming12713** [apache/doris-operator#76]
hi 
follow  smaple  [doriscluster-sample-storageclass ](https://github.com/selectdb/doris-operator/blob/master/doc/examples/doriscluster-sample-storageclass.yaml )create doris cluster ,not resolve be name 

```

curl  --location-trusted -u root:000000 -T cc.csv -H "column_separator:," http://10.0.162.252:31352/api/demo/example_tbl/_stream_load

curl: (6) Could not resolve host: doriscluster-be-0.doriscluster-be-internal.doris.svc.cluster.local
```

**Comment by intelligentfu** [comment]
In K8s, stream load should direct use `be access` service.  In stream load fe as 301 proxy. In fact, client direct interaction with be, but in k8s, be address not be direct accessed by client that out k8s.

**Comment by ming12713** [comment]
> In K8s, stream load should direct use `be access` service. In stream load fe as 301 proxy. In fact, client direct interaction with be, but in k8s, be address not be direct accessed by client that out k8s.

Is there an alternative solution, such as using 'hostNetwork,' to resolve the issue without using a service?

**Comment by intelligentfu** [comment]
using hostNetWork is not a good choice. Kubernetes does not recommend hostnetwork mode. hostNetwork is not universal.
 From use:
 if using hostNetwork, the IP will change when the pod moves to node2 from node1. fe and be will not work normally.  other, using hostnetwork the service will not work.

**Comment by ming12713** [comment]
> using hostNetWork is not a good choice. Kubernetes does not recommend hostnetwork mode. hostNetwork is not universal. From use: if using hostNetwork, the IP will change when the pod moves to node2 from node1. fe and be will not work normally. other, using hostnetwork the service will not work.

Are there any other recommended methods? if we want to access doris out of k8s;

**Comment by intelligentfu** [comment]
for stream load, you can use access be service and service use NodePort or lb.

**Comment by intelligentfu** [comment]
I closed the issue for a long time reply.  if you are still confused, please reopen the issue.
