### ISSUE TITLE
Doris 2.1 show frontends  return adjusted

### ISSUE THREAD

**Issue by catpineapple** [apache/doris-operator#95]
Return result adjustment affects cluster initialization and master node acquisition, requiring adaptation.

mysql> show frontends;
+-----------------------------------------+----------------------------------------------------------------------------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+------------------------------+------------------+
| Name                                    | Host                                                                             | EditLogPort | HttpPort | QueryPort | RpcPort | ArrowFlightSqlPort | Role     | IsMaster | ClusterId | Join | Alive | ReplayedJournalId | LastStartTime       | LastHeartbeat       | IsHelper | ErrMsg | Version                      | CurrentConnected |
+-----------------------------------------+----------------------------------------------------------------------------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+------------------------------+------------------+
| fe_0dba4cb9_55a4_44ac_b82c_a81d8137532f | [doriscluster-sample-fe-0.doriscluster-sample-fe-internal.doris.svc.cluster.local](http://doriscluster-sample-fe-0.doriscluster-sample-fe-internal.doris.svc.cluster.local/) | 9010        | 8030     | 9030      | 9020    | -1                 | FOLLOWER | true     | 847488715 | true | true  | 39                | 2024-01-16 05:26:10 | 2024-01-16 05:28:41 | true     |        | doris-0.0.0-trunk-9ef4e49307 | Yes              |
+-----------------------------------------+----------------------------------------------------------------------------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+------------------------------+------------------+
1 row in set (0.00 sec)

**Comment by intelligentfu** [comment]
https://github.com/selectdb/doris-operator/pull/105
